no terminal: conda env export

copiar e colar dentro de environment

name: D:\ProgramFiles\anaconda\env\machine_learning
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - altair=5.0.1=py312haa95532_0
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h2bbff1b_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=16.1.0=h7cd61ee_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=py312haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.10.55=hd77b12b_0
  - babel=2.16.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyhd8ed1ab_0
  - blinker=1.6.2=py312haa95532_0
  - blosc=1.21.3=h6c2663c_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py312h4b0e54e_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.1.31=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=py312haa95532_0
  - cairo=1.16.0=hc68a040_5
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py312h827c3e9_0
  - cfitsio=3.470=h0af3d06_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312haa95532_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h5da7b33_0
  - fiona=1.9.5=py312hc7c4135_0
  - folium=0.19.4=pyhd8ed1ab_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.51.0=py312h2bbff1b_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=ha860e81_0
  - freexl=2.0.0=h8276f4a_0
  - gdal=3.6.2=py312h8827949_7
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.8.0=he025d50_1
  - geotiff=1.7.0=h4545760_3
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py312haa95532_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - glog=0.5.0=hd77b12b_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.13=h0e5069d_1005
  - hdf5=1.12.1=h51c971a_3
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py312haa95532_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py312haa95532_0
  - ipympl=0.9.4=pyhd8ed1ab_0
  - ipython=8.29.0=pyh7428d3b_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - ipywidgets=7.8.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhff2d567_0
  - jinja2=3.1.4=py312haa95532_1
  - joblib=1.4.2=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.28=pyhff2d567_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.23.0=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312haa95532_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.11=pyhd8ed1ab_0
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.4=py312hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.9.1=h0416ee5_0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h56d1f94_1
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=h0e70117_7
  - libglib=2.78.4=ha17d25a_0
  - libgrpc=1.62.2=hf25190f_0
  - libiconv=1.17=hcfcfb64_2
  - libkml=1.3.0=h63940dd_7
  - libnetcdf=4.8.1=h6685c40_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.0=h70ee33d_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h5a68840_5
  - libspatialite=5.1.0=h25d3e1c_1
  - libssh2=1.11.0=h291bd65_0
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.1=h24da03e_2
  - libzip=1.8.0=h519de47_1
  - lz4-c=1.9.4=h2bbff1b_1
  - mapclassify=2.8.1=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=py312haa95532_1
  - markupsafe=2.1.3=py312h2bbff1b_0
  - matplotlib=3.9.2=py312haa95532_0
  - matplotlib-base=3.9.2=py312hbdc63d0_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.0=py312haa95532_0
  - minizip=4.0.3=hb68bac4_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.4.2=pyh267e887_2
  - nodejs=22.11.0=h57928b3_0
  - notebook=7.3.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numexpr=2.10.1=py312h4cd664f_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.1=ha4e3fda_0
  - orc=2.0.1=hd8d391b_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=py312haa95532_0
  - pandas=2.2.2=py312h0158946_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h827c3e9_0
  - pip=24.2=py312haa95532_0
  - pixman=0.43.4=h63175ca_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=py312haa95532_1
  - poppler=24.09.0=h4f47ea2_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - proj=9.3.1=ha107b6e_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - protobuf=4.25.3=py312h958608f_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyarrow=16.1.0=py312h0158946_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydeck=0.8.0=py312haa95532_2
  - pygments=2.15.1=py312haa95532_1
  - pyparsing=3.2.0=py312haa95532_0
  - pyproj=3.6.1=py312h8115771_0
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.5=h14ffc60_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pywinpty=2.0.10=py312h5da7b33_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.2=h19c9488_11
  - re2=2022.04.01=hd77b12b_0
  - referencing=0.30.2=py312haa95532_0
  - requests=2.32.3=py312haa95532_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.1=py312haa95532_0
  - rpds-py=0.10.6=py312h062c2fa_0
  - rtree=1.0.1=py312h2eaa2aa_0
  - scikit-learn=1.5.1=py312h0158946_0
  - scipy=1.14.1=py312h9d85e7c_0
  - seaborn=0.13.2=py312haa95532_0
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=75.1.0=py312haa95532_0
  - shapely=2.0.5=py312h4059a34_0
  - sip=6.7.12=py312hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.37.1=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=8.2.3=py312haa95532_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tiledb=2.3.3=hd8964de_3
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.1.0=pyhff2d567_0
  - toolz=0.12.0=py312haa95532_0
  - tornado=6.4.1=py312h827c3e9_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.11.0=py312haa95532_0
  - typing_extensions=4.11.0=py312haa95532_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.2.3=py312haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - watchdog=4.0.1=py312haa95532_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=py312haa95532_0
  - widgetsnbextension=3.6.10=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - xerces-c=3.2.5=he0c23c2_2
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=he0c23c2_3
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - python-dotenv==1.0.1
prefix: D:\ProgramFiles\anaconda\env\machine_learning